apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
  labels:
    app: eqs-test
    env: production
spec:
  replicas: 2
  selector:
    matchLabels:
      app: eqs-test
      env: production
  template:
    metadata:
      labels:
        app: eqs-test
        env: production
    spec:
      containers:
      - name: nginx
        image: ghcr.io/vault60/eqs-challenge/esq-nginx:prod
        #image: docker.pkg.github.com/vault60/eqs-challenge/esq-nginx:prod
        ports:
        - containerPort: 80
      imagePullSecrets:
      - name: regcred-ghcr
